### ISSUE TITLE
Prossesing issue by GlapTop2-py

### ISSUE THREAD

**Issue by akashbasotra** [WilcoTerink/GlabTop2-py#11]
![problem](https://github.com/WilcoTerink/GlabTop2-py/assets/173379096/f412b0f0-94c7-4b96-80c7-b8e4abc6bf9d)
my issue is that, i started processing and waited for 6-7 hrs but still got no output. Also, i was not able to figure out whether the processing is going on or not or how much processing is completed or left.  Please help me in this matter and provide some instructions so that i can complete the processing of glacier with few time left. 
please reply me , i have provided my email id below.

Name :- Akash Basotra
Email:- abasotra44@gmail.com

**Comment by WilcoTerink** [comment]
Hi. Is it maybe that you have an extremely small cell resolution, resulting in an enormous number of cells (rows x columns) to process? It should generally not take too long, but it might do if you have many many cells....

**Comment by fangxiao666** [comment]
Dear author, I am sorry to bother you.
My first question is, in line 149 of the “main.py” file, should the code “if dH > 1600” be changed to “if dH > 1.6 “? 
The second question is, in the “config.cfg” file, why is “hga = 0 for the adjecent cells” used instead of “hga = 15 for the marginal cells” used in the literature?
![question1](https://github.com/user-attachments/assets/a8a246f5-5314-42d9-9ee4-45817eaf28b5)
![question2](https://github.com/user-attachments/assets/074016c5-b22e-482c-bf75-75b497df2513)
I apologize for the bad English and look forward to your reply!
Name :-  Xiaonan Fang
Email  :-  20191001632@cug.edu.cn

**Comment by WilcoTerink** [comment]
Hi,Thanks for looking into the code.I’ll look into your first question in the next couple of days. Please remind me if I haven’t done so.Re the hga value. It represents the ice thickness of glacier adjacent cells, i.e., non glacier cells. In my default config values I have assumed there is no other glacier next to your glacier of interest. So ice thickness is zero in that case. However, if you have another neighboring glacier, you could fill in a value higher than zero. Regards WilcoOn 30 Oct 2024, at 13:39, fangxiao666 ***@***.***> wrote:﻿
Dear author, I am sorry to bother you.
My first question is, in line 149 of the “main.py” file, should the code “if dH > 1600” be changed to “if dH > 1.6 “?
The second question is, in the “config.cfg” file, why is “hga = 0 for the adjecent cells” used instead of “hga = 15 for the marginal cells” used in the literature?
question1.jpg (view on web)
question2.jpg (view on web)
I apologize for the bad English and look forward to your reply!
Name :-  Xiaonan Fang
Email  :-  ***@***.***

**Comment by gurnamparsad** [comment]
(gurnam) D:\Glabtop Parameters>gdal_translate -of PCRaster -ot Float32 -mo VS_SCALAR Rangbok_dem.tif Rangbok_dem.map
Input file size is 1360, 1207
0...10...20...30...40...50...60...70...80...90...100 - done.

(gurnam) D:\Glabtop Parameters>gdal_translate -of PCRaster -ot int32 -mo VS_NOMINAL Rangbok_grid.tif Rangbok_grid.map
Input file size is 1360, 1207
0...10...20...30...40...50...60...70...80...90...100 - done.

(gurnam) D:\Glabtop Parameters>cd D:\GlabTop2-py-master\GlabTop2\app

(gurnam) D:\GlabTop2-py-master\GlabTop2\app>streamlit run main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.170.2.190:8501

Traceback (most recent call last):
  File "C:\Users\gis12.GISLAB1.000\AppData\Local\anaconda3\envs\gurnam\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gis12.GISLAB1.000\AppData\Local\anaconda3\envs\gurnam\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gis12.GISLAB1.000\AppData\Local\anaconda3\envs\gurnam\GlabTop2\main.py", line 313, in <module>
    main(sys.argv[1:])
  File "C:\Users\gis12.GISLAB1.000\AppData\Local\anaconda3\envs\gurnam\GlabTop2\main.py", line 304, in main
    glabtop.run()
  File "C:\Users\gis12.GISLAB1.000\AppData\Local\anaconda3\envs\gurnam\GlabTop2\main.py", line 253, in run
    [glacmask, mCells, innerCells] = self.identifyCells(gID)
  File "C:\Users\gis12.GISLAB1.000\AppData\Local\anaconda3\envs\gurnam\GlabTop2\main.py", line 102, in identifyCells
    if glacMask[r+1,c+1] == self.mv:
IndexError: index 1360 is out of bounds for axis 1 with size 1360

I am having this problem in running the Glabtop2-py, please give me some suggestion.
Email:- gurnam.parsad@jamuuniversity.ac.in

**Comment by WilcoTerink** [comment]
This is likely because your input maps do not have the same resolution and or spatial extent.
