### ISSUE TITLE
Some problems of the GlabTop2

### ISSUE THREAD

**Issue by ghost** [WilcoTerink/GlabTop2-py#8]
Hi Wilco,
I used the GlabTop2 code you posted on GitHub to perform calculations on glacier thickness in the southeastern region of the Tibetan Plateau. But there may be some problems with the results I got (as shown in the picture), you can see several places where the thickness of the glacier is close to 0, such as Galapai Peak and Nanga Barwa Peak on the left. The glacier boundary shapefile I entered was extracted by myself, and I used NASA's 30m dem and set the interval to 50m. Could you please tell me the reason?
I tried to send a mail to you but it didn't work, if you are convenient could you please contact me? My mail address is douxyz1994@gmail.com. 
Thanks and best regards.
![image](https://user-images.githubusercontent.com/58248905/183342362-501cf062-dd79-448b-8ffc-20603bdaf753.png)

**Comment by WilcoTerink** [comment]
Hi,

I suggest you read this article, especially the appendix of it: https://tc.copernicus.org/articles/8/2313/2014/tc-8-2313-2014.pdf

If there's not much variation in the dem for the glaciers you mention, then ice depths likely won't vary much as well. Using higher r values can help.

**Comment by ghost** [comment]
thanks for your reply, I did not understand what "not much variation in the dem for the glaciers you mention" means, I had contacted the author of this paper and he didn't think there was anything wrong with my input data, so he suggested I come and consult you. In addition, I have used glacier profiles from three different periods and the same dem to perform thickness calculations, but the results of one of the periods differed dramatically from the other two, with differences in glacier thickness of up to several hundred meters, which also puzzled me.

**Comment by Andrea-Vergnano** [comment]
Hello Wilco,
Thank you for sharing this interesting model.
A few years ago, it worked fine, but now, with all the new versions of Conda and Python my colleagues and I struggle to make it work.
I tried creating a conda virtual environment with python 3.8 instead of 3.9, but it was not enough. The command conda install -c WilcoTerink GlabTop2-py fails to solve the environment, there is always some missing dependency and, as for now, I'm not very practical of conda.

It would be very useful if you update the documentation to specify what the users are supposed to do to make it work, considering that they will download the latest version of anaconda.

THANK YOU!!
Andrea
